# Generated by Django 3.0.8 on 2020-08-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_cart_category_comment_list_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='currentbid',
            field=models.CharField(default='No Bid', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='avatar.png', upload_to='profile_Pic'),
        ),
    ]
