# Generated by Django 3.0.8 on 2020-08-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200809_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='profilepic/avatar.png', upload_to='profile_Pic'),
        ),
    ]
