# Generated by Django 3.0.8 on 2020-08-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20200809_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='check',
        ),
    ]
