# Generated by Django 3.0.8 on 2020-08-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200810_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='image',
            field=models.ImageField(blank=True, upload_to='List/'),
        ),
    ]
