# Generated by Django 3.0.8 on 2020-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20200813_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='winner',
            field=models.TextField(default='', max_length=255),
        ),
    ]
