# Generated by Django 3.0.8 on 2020-08-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_list_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='winner',
            field=models.TextField(default='', max_length=255, null=True),
        ),
    ]
