# Generated by Django 3.0.8 on 2020-08-15 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20200815_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='currentbids',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='list',
            name='currentbid',
            field=models.CharField(default='No Bid', max_length=10),
        ),
    ]
