# Generated by Django 3.0.8 on 2020-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20200817_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='selected',
            field=models.BooleanField(default='False'),
        ),
    ]
