# Generated by Django 3.0.8 on 2020-08-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_bid_selected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
